apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgAwEFXgCeQrxrfxSDwmCrx9MQQT9QxQr2anl3ywik5i3lIJqMLEMUtgtvse0oxxkZzBSsgbVqx0Q0PDI7VGSVx4n/+AEurNaCaF/dUbe48PqlNsoacchB4nw9pUfvvJs7V+T/ntAEdCZjO3g5mAXCUkXuQ9Nbc34FBMU+wkwArNZrv5HkJvtCHY8USyg9NS6ZOR3OMeFp7vdI3RN6Fp090qbd1jMY0iSRIY86LqQVePYq/zIN/c1B4zGgr7UDNwNZsHM197LWEPF8lLzX1+wmNXo3H0xR9cGrvXRIUKlGRckD0ZUvIHkKWHVq55wbGpSS+ru+UEcg2grqjgfLj1ENbCIUJr51rGh6RTxferGBSXHs+sp2KZstirhyzOxeK4okEC53ZuVjs2NFvzqWKwLjkRX7EfDhR3lLQMbnVxpNxG6A8KGWegKCujNsMZe4qkoar/hXyqZ/vJiMIpDGoP9hMKCb+kZzq3K0XgP/8eRDIbTixEdgtcSl/C81KPUoGqdd5/6QXc7Fleiz17JCzB/Jq0Q1R71vLXG2juGiVn+ueoBQ+bsuKehld4XOSTFdi66HnpGjXzm4K5j/MGiZHSjmfB8b0ySKsQ6K7cz2pAx/sfFHkQKwdj9RJBxuImHUhgaX2O9UKqnpeQKXhu9m3U+PGlcsX1qHav9IKVzNqweHYJ43gcFwleW62Yk6dBUtCnZLro9abTnZjlug==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

